meta_product_name: "Harrytimbog's blog"
meta_title: "Harrytimbog's blog - no one is a stranger"
meta_description: "A platform for hungry writers and lovers of fun"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@harrytimbog1"   # required for Twitter Cards
